# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Copy the Python scripts and token.txt file into the container
COPY music_cog.py Main.py help_cog.py token.txt /app/

# Install necessary Python dependencies
RUN pip install discord.py youtube_dl

# Set the command to run your bot (replace YOUR_BOT_TOKEN with your actual bot token)
CMD ["python", "Main.py"]
